### ISSUE TITLE
graphqlProxy does not work in offline accessMode

### ISSUE THREAD

**Issue by johna1203** [Shopify/shopify-node-api#140]
# Issue summary

when accessMode is offline graphql_proxy doesn't work.

## Expected behavior

you need to pass a parameter to the graphqlProxy to let it know the accessMode.
https://github.com/Shopify/shopify-node-api/blob/766317d6419d0f8b1600e917f63de21f91f65106/src/utils/graphql_proxy.ts#L9

## error details
As the accessMode is not being passed to the graphql_proxy, it tries to get the online session as it does not exist and throws a throw below. 

https://github.com/Shopify/shopify-node-api/blob/766317d6419d0f8b1600e917f63de21f91f65106/src/utils/graphql_proxy.ts#L11

```
  Error: Cannot proxy query. No session found.
      at SessionNotFound.ShopifyError [as constructor] (/home/ubuntu/src//node_modules/@shopify/shopify-api/dist/error.js:13:28)
      at new SessionNotFound (/home/ubuntu/src//node_modules/@shopify/shopify-api/dist/error.js:140:42)
      at Object.<anonymous> (/home/ubuntu/src//node_modules/@shopify/shopify-api/dist/utils/graphql_proxy.js:17:31)
      at step (/home/ubuntu/src//node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/ubuntu/src//node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/home/ubuntu/src//node_modules/@shopify/shopify-api/node_modules/tslib/tslib.js:114:62)
```

**Comment by paulomarg** [comment]
Hey @johna1203, this is actually done by design, because offline tokens shouldn't be used for direct user interactions - your app shouldn't allow the client side to run GraphQL queries directly using offline tokens (e.g. via the proxy), so you should instead use online tokens or define your queries in your app's backend.

**Comment by johna1203** [comment]
Hey @paulomarg , thank you for answering.
I'm sorry, I thought it was a bug. :)

But, In my case I need to generate an offline token because i am also registering webhooks in my app. i had problems with online token in webhooks because it expires. so i switched to offline token.

do you have any example, where i can generate two tokens? one online to the GraphQL proxy and one offline to the webhooks?
what is the best practice for my case?

Thanks,

**Comment by paulomarg** [comment]
You can actually use both types of token depending on your needs, the library supports that. You can use the `loadCurrentSession(req, res)` and `loadOfflineSession(shop)` utilities to load the session depending on which case you're using.

Note that `loadOfflineSession` should not take the shop name from user input as it assumes the request is coming from your app's backend.

You'll need to perform a separate OAuth process for each token, but since offline tokens never expire users will only have to it once. The online token can then be regenerated as needed when users are interacting with the app directly.

**Comment by ivorpad** [comment]
@paulomarg How do we get the session with `loadCurrentSession(req, res)` if cookies are not allowed in embedded apps?

`loadCurrentSession` validates the request by checking if the `shopify_app_session` exists. I'm currently using `loadOfflineSession` in the backend but I'd like to do GraphQL requests on the client.

**Comment by rafaelsorto** [comment]
Were you able to solve that issue @ivorpad ? I am facing the same problem. Graphql requests on frontend are Forbidden if access mode is offline.

**Comment by alexandrosk** [comment]
> 

Did you find a solution to this? I'm trying to use graphqlProxy but I only have offline session from the React app -> to Node
