### ISSUE TITLE
Http Client depends on obsolete package 'fs'

### ISSUE THREAD

**Issue by bumasoft** [Shopify/shopify-node-api#147]
Hello,

I get this error when trying to include the @shopify/shopify-api package in my project:

./node_modules/@shopify/shopify-api/dist/clients/http_client/http_client.js:7:0
Module not found: Can't resolve 'fs'

Checking that file, it seems that indeed that script is trying to use 'fs', on line 7:

var fs_1 = tslib_1.__importDefault(require("fs"));

That package is not available anymore on the NPM repository: https://www.npmjs.com/package/fs

**Comment by paulomarg** [comment]
Hey @bumasoft, the `fs` package is actually built into Node: https://nodejs.org/api/fs.html, so we're not using that outdated external package.

There's not much we can do from the library side for that, but I think you might be able to fix that by tweaking your webpack settings.

I'm going to close the ticket since we can't fix it from our code, but please reopen it if you spot any issues with our code!

Hope this helps!

**Comment by bumasoft** [comment]
@paulomarg I believe that's referenced on the client side, though, which is why the error occurs. I'll check if I can fix this from webpack, thanks for responding.

**Comment by paulomarg** [comment]
Good point! This package only contains backend code, it shouldn't be included on the client side. Maybe you could filter it out while packing for the client side?

**Comment by bumasoft** [comment]
@paulomarg You were right, my app was referencing the package on the client side somewhere. Thanks a lot, enjoy your day!
