### ISSUE TITLE
How do I customize the session?

### ISSUE THREAD

**Issue by jezsung** [Shopify/shopify-node-api#182]
The package gives us `CustomSessionStorage` and requires to implement 3 callbacks which are `storeCallback`, `loadCallback`, `deleteCallback`. The `storeCallback` method requires `Session` argument when using Typescript. How do I store my own session data? For example, let's say I want to store the online and offline access token at the same time, but it looks like the current implementation only allows one token. And even if I can extend `Session` with my own class, I'm forced to store `shop`, `state` and `scope`. I'm not sure what the `state` property is for. Is there any way I can further customize it?

``` typescript
class Session {
    readonly id: string;
    static cloneSession(session: Session, newId: string): Session;
    shop: string;
    state: string;
    scope: string;
    expires?: Date;
    isOnline?: boolean;
    accessToken?: string;
    onlineAccessInfo?: OnlineAccessInfo;
    constructor(id: string);
}
```

**Comment by thecodepixi** [comment]
Hey! So you can definitely create a custom session class that can be as extensible as you need/want it to be. What you'll want to do is: 

- create a `CustomSession` class that looks something like this: (make sure it `extends Shopify.Session.Session`)
```ts
import Shopify from '@shopify/shopify-api' 

class CustomSession extends Shopify.Session.Session {
  foo: string;
  bar: number[]; 
  ... other custom data ... 
}
```

- Then make sure your `loadCallback` _returns an instance of that `CustomSession` class_ so that the library treats it as an instance of `Session`

- When you load your sessions, in order to access your custom fields, you'll want to cast the return as your `CustomSession` class: 
```ts
let session = await Shopify.Utils.loadCurrentSession(req, res) as CustomSession;
```

Hope that's helpful! Let me know if that doesn't answer your question or if anything is unclear.

**Comment by jezsung** [comment]
@thecodepixi  Thanks for your answer! But doesn't it force to implement `shop`, `state`, and `scope` properties? Sorry if it isn't, I'm pretty new to Typescript. And what the `state` property is for? Isn't it the random number we should generate during OAuth flow for security? I don't know why we would want to store in the sessions.

**Comment by thecodepixi** [comment]
Yes, these parameters are all required for the OAuth process. You cannot remove them from your sessions because they are required for many features of the library to function correctly.

**Comment by jezsung** [comment]
@thecodepixi Thanks it really helped me a lot. But I'm wondering how the library automatically store and load the online and offline access token separately. 

The library has two methods to fetch the session from the database. 
``` typescript
await Shopify.Utils.loadCurrentSession(request, response, isOnline);
await Shopify.Utils.loadOfflineSession(shop);
```
But the `Session` class only has one access token property.
``` typescript
class Session {
    readonly id: string;
    static cloneSession(session: Session, newId: string): Session;
    shop: string;
    state: string;
    scope: string;
    expires?: Date;
    isOnline?: boolean;
    accessToken?: string;
    onlineAccessInfo?: OnlineAccessInfo;
    constructor(id: string);
}
```
I thought I can store the online and offline access tokens by implementing my own session class, store, and load callbacks, but the fact that the library already has the methods for fetching both of them is kind of confusing.

So how does the library store and load the online and offline access tokens at the same time? Or is it impossible to fetch them concurrently?

**Comment by thecodepixi** [comment]
Online and offline sessions are stored separately. So if you have a the offline access token from a particular shop, that offline session will be separate from any/all online sessions that are created (which will store the access tokens for those session). It is important not to tie them together and store those tokens in the same place, because offline tokens are permanent and do not expire, but the expectation is that an online sessions token and data is only stored for the duration of that session. I hope that helps!

**Comment by jezsung** [comment]
@thecodepixi Thanks! That really helped, I think I can close the issue.
