### ISSUE TITLE
Allow mutations with GraphQLClient 

### ISSUE THREAD

**Issue by noahbaron91** [Shopify/shopify-node-api#201]
## Overview
Allow mutations with GraphQLClient and not just queries.

...

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?
Wanting to make mutations using the shopify GraphQLClient
...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [X ] I have described this feature request in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hey @noahbaron91, thank you for your request!

The `query` method from that class already supports any GraphQL request, including mutations. We even use it within the library to run a mutation to set up [webhook subscriptions](https://github.com/Shopify/shopify-node-api/blob/main/src/webhooks/registry.ts#L219-L221) (the mutation is built [here](https://github.com/Shopify/shopify-node-api/blob/345d6edb24805037e2952f252536dce5e2a17a33/src/webhooks/registry.ts#L163-L173)).

I'm closing this issue since we already provide the requested support, but if you have any specific issues while running mutations, please feel free to open other issues!
