### ISSUE TITLE
Transient shopify error (for html response instead of json) is thrown as HttpRequestError instead of HttpRetriableError

### ISSUE THREAD

**Issue by wszaranski** [Shopify/shopify-node-api#257]
# Issue summary

Sometimes query returns non json response (probably html but only parsing error is logged). 
This error is wrongly interpreted as request error and isn't retried.

## Expected behavior

`HttpRetriableError` should be thrown instead of `HttpRequestError`

## Actual behavior

When we get non json response [HttpRequestError](https://github.com/Shopify/shopify-node-api/blob/975b87985c57cc723488a9f712de39a28ce2c967/src/clients/http_client/http_client.ts#L264-L266) which is caused by [response.json()](https://github.com/Shopify/shopify-node-api/blob/975b87985c57cc723488a9f712de39a28ce2c967/src/clients/http_client/http_client.ts#L180) parsing `HttpRequestError` is thrown.

<details>
Failed to make Shopify HTTP request: FetchError: invalid json response body at https://XXX.myshopify.com/admin/api/2021-07/products.json?limit=250&page_info=XXX reason: Unexpected token < in JSON at position 0
</details>

## Steps to reproduce the problem

It's hard to provide reproduce steps for transient error but I'll provide PR with this situation handled in test case.

**Comment by mllemango** [comment]
Hey @wszaranski, thanks for putting in a PR for your issue. I'm going to ask that we hold off on your proposed solution since the problem I want to tackle is why you're seeing intermittent HTML responses in the first place. 
What are your thoughts on adding an [Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) instead and seeing if you're still running into this issue?
